name: test-pr-wf
on:
  pull_request_target: # Use pull_request_target
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i have modify the pr wf" # modify the pr file 

      - run: echo "$EVENT"
        
