name: test-push-wf
on:
  push: # ordinary push event for merge to master
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}